@echo off
echo Starting AI Dropout Prediction Service...
echo Make sure you have Python and required packages installed
echo Installing required packages...
pip install -r backend\ai\requirements.txt
echo Starting Flask API server on port 5002...
cd backend\ai
start "AI Service" python api.py
pause